
project_id = "dywlonihwrnutwvzqivo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[functions]
enabled = true
verify_jwt = false

[functions.rfp-multi-agent]
verify_jwt = false

[functions.rfp-realtime-analysis]
verify_jwt = false

[auth]
enabled = true
port = 54321
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enabled = true
double_confirm_changes = true
enable_confirmations = false
template_path = "./supabase/templates"

[edge-runtime]
enabled = true
port = 54288
inspector_port = 54289

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"
