
project_id = "dywlonihwrnutwvzqivo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://dywlonihwrnutwvzqivo.lovableproject.com"]
jwt_expiry = 3600

[functions.rfp-multi-agent]
verify_jwt = false

[functions.rfp-realtime-analysis]
verify_jwt = false

[functions.web-scraper]
verify_jwt = false

[functions.advanced-scraper]
verify_jwt = false

[edge-runtime]
enabled = true
port = 54327

[analytics]
enabled = false
