// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dywlonihwrnutwvzqivo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5d2xvbmlod3JudXR3dnpxaXZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTc4OTgsImV4cCI6MjA2OTEzMzg5OH0.4xkhJ-ETqHWqvWPzqQByGcfZmV4ybyS9K4lad0PL1Sk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});